### ISSUE TITLE
Add backtick as a quote

### ISSUE THREAD

**Issue by dmnd** [atom/toggle-quotes#14]
Sometimes I get halfway through writing a string when I realise I want to use ES6 interpolation. It'd be nice to be able to use toggle quotes here.

**Comment by lope** [comment]
+1 I get this too.

I would like it to cycle through each type of quote every time you press the hot key.
```
"foo"
'foo'
`foo`
```

**Comment by alexrussell** [comment]
Probably worth closing this issue.

**Comment by vcarel** [comment]
Hi, I added the backquote to the `quoteCharacters` just as shown above, and it works. But from a back-quoted string I cannot come back to a single- or a double-quoted one.
