### ISSUE TITLE
It stopped working after latest atom update - Version 0.211.0 (0.211.0)

### ISSUE THREAD

**Issue by prabackar** [atom/toggle-quotes#25]

**Comment by prabackar** [comment]
The shortcut or Packages menu doesn't do anything!

In dev mode, 
1) JSON file works.
2) JS file - variable works
var a = 'test';
3) function returning an object doesnt' work

Normal mode,
none of it works

**Comment by prabackar** [comment]
It started to work now. May be system restart helped.

**Comment by jsg2021** [comment]
It still doesn't work for me 99% of the time.

Here is an example snippet:

```es6
import React from 'react';


let {basePath = '/'} = global.$AppConfig || {};

import AppView from './AppView';

let app = React.render(
	React.createElement(AppView, {basePath}),
	document.getElementById('content')
);

global.onbeforeunload = () => app.setState({mask: 'Reloading...'});
```

interestingly, if the destructured statement is switched to just a variable declaration/assignment many of the strings become togglable. But not all. `'content'` seems to not be togglable at all.

**Comment by jsg2021** [comment]
I still cannot get it to work. Even when i invoke the command from the pallet.
