### ISSUE TITLE
Doesn't work if a line contains multiple sets of quotes.

### ISSUE THREAD

**Issue by tjbenton** [atom/toggle-quotes#32]
It only works on the first set of quotes in the line, but not the second set of quotes.

![example](http://g.recordit.co/onc7Su7JRO.gif)

I'm on a Macbook Pro - version 10.10.4
Atom - version 1.0.7(installed through brew)

**Comment by thomasstep** [comment]
This is not an issue for me. I know that this is an old issue, so it might have been fixed.

**Comment by Arcanemagus** [comment]
Looks like this was fixed at some point since it was filed, thanks for letting us know!
