### ISSUE TITLE
It eats the characters below

### ISSUE THREAD

**Issue by unluisco** [atom/toggle-quotes#34]
Begins to eat them :dizzy_face:

![quotes](https://cloud.githubusercontent.com/assets/6332263/9664566/5960c2b0-5230-11e5-9803-93b23c9847f6.gif)

**Comment by Aerijo** [comment]
I can't reproduce, and this is quite old, so I'm going to close as fixed. Feel free to reopen and add steps to reproduce if it's still an issue.
