### ISSUE TITLE
Issue with keyboard shortcut

### ISSUE THREAD

**Issue by PhiLhoSoft** [atom/toggle-quotes#37]
More FYI than for bug report...

I added the package to Atom 1.3.1 on Win7. I wanted to try it, Ctrl+" doesn't work (kind of feared that...).
Note: I have a French keyboard, azerty, so some shortcuts with Ctrl and non-letter characters do not work, sometime because the symbol must be shifted, sometime just because...

I searched the shortcut in the Settings > Keybindings page. I could not find it...
I found it in the project page, so I added it to `keymap.cson`, mapping to Ctrl+Q, which is not used.
After adding it:
- it worked! (thanks)
- I could see this keybinding, and the default one (!) in the above mentioned page.

**Comment by lee-dohm** [comment]
Thanks for the FYI! We're tracking the issues with International keyboards in https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37.

As for the issue with not being able to find the key binding, I wasn't able to reproduce the issue using Atom v1.5.0-dev-f6da4a9 on Mac OS X 10.11.2. If you can reproduce it, please file a bug on the https://github.com/atom/settings-view repository.

Thanks again!
