### ISSUE TITLE
stopped working on Atom 1.9.6

### ISSUE THREAD

**Issue by stoplion** [atom/toggle-quotes#40]

**Comment by 50Wliu** [comment]
Please provide more information.  See https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report.

**Comment by stoplion** [comment]
Atom version `1.9.6`
Latest toggle-quotes
place cursor in the string scope, open command palette, summon the change quote command. 
Doesn't change quote :(
