### ISSUE TITLE
Doesn't work with es6 import and language-babel

### ISSUE THREAD

**Issue by branchard** [atom/toggle-quotes#49]
It doesn't work with es6 import and [language-babel package](https://github.com/gandm/language-babel).

![peek 11-06-2017 01-01](https://user-images.githubusercontent.com/6990948/27006904-79229394-4e41-11e7-8b10-70b16d706c9f.gif)

OS : Linux
Atom version : 1.17.2

**Comment by gandm** [comment]
@branchard Hi I've fixed this in language-babel https://github.com/gandm/language-babel/commit/f9e999d5f6d53baae0ac4f530757661199772e61 so you can close this issue. Not sure when I'll publish but you can `apm install` from the git repo.

**Comment by branchard** [comment]
@gandm Ok, thank you !
