### ISSUE TITLE
Unquote

### ISSUE THREAD

**Issue by danielbayley** [atom/toggle-quotes#50]
It would be nice to have a separate `toggle-quotes:unquote` command, and/or also add this to the current toggle rotation.

**Comment by jasonrudolph** [comment]
Thanks for the idea!

I could see this being useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this package. This package is tightly focused on toggling between various types of quotes; it doesn't aim to handle completely unquoting a string. 😇 
 For that reason, I'm going to close this issue. It might be a cool idea for an Atom package though. If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

Thanks again for contributing to Atom 🙇
