### ISSUE TITLE
Feature Request: Scoped Settings

### ISSUE THREAD

**Issue by wottpal** [atom/toggle-quotes#55]
Hey,
it would be great to add settings (quote characters) for each language separately.

Background: If I add the backtick ` to the quote characters this works fine in JavaScript files but when I switch to PHP the plugin always stops working when I've toggled until the backtick like mentioned in #35.

Thanks!
Dennis

**Comment by mattyclarkson** [comment]
This is [documented](https://github.com/atom/toggle-quotes#configuration) on the README. Is that not what you are looking for?

**Comment by Ben3eeE** [comment]
Thanks @mattyclarkson :bowing_man:
