### ISSUE TITLE
Seemingly broken with Tree Sitter Parsers for Ruby on 1.32.0

### ISSUE THREAD

**Issue by gmkohler** [atom/toggle-quotes#64]
### Description

On Atom 1.32.0, with the Tree Sitter Parser and Ruby syntax settings on, the toggle quotes command is not toggling quotes.  The toggling still works for Ruby On Rails and JavaScript langauges as two counter-examples

### Steps to Reproduce

1.  Open a file with the Ruby language setting
2. Try to toggle quotes with the toggle quotes command

**Expected behavior:**
The quotes to toggle

**Actual behavior:**
No toggling

**Reproduces how often:**
100%

### Versions
macOS 10.13.4

Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.15
git 2.19.0

### Additional Information

Not sure if this repo, `language-ruby` repo, or `atom` repo is the best place to file this, happy to re-file in the appropriate place.

**Comment by Ben3eeE** [comment]
:wave: Thanks for taking the time to file an issue :bowing_man: 

I am unable to reproduce the issue you describe. Are you on the latest version of this package? Can you share some code snipper the toggling quotes doesn't work?

**Comment by gmkohler** [comment]
I was on `1.1.0`.  `1.1.1` works, sorry!
